[package]
name = "sys-mount"
version = "1.5.1"
description = "High level FFI binding around the sys mount & umount2 calls"
repository = "https://github.com/pop-os/sys-mount"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
license = "MIT"
readme = "README.md"
keywords = ["linux", "sys", "mount", "umount"]
categories = ["external-ffi-bindings", "filesystem", "os::unix-apis"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
bitflags = "1.3.2"
libc = "0.2.119"
loopdev = { version = "0.4.0", optional = true }
smart-default = "0.6.0"
thiserror = "1.0.30"
tracing = "0.1.31"

[features]
default = ["loop"]
loop = ["loopdev"]

[dev-dependencies]
clap = "2.33.3"
